#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libfastjson
Version  : 0.99.8
Release  : 3
URL      : https://github.com/rsyslog/libfastjson/archive/v0.99.8.tar.gz
Source0  : https://github.com/rsyslog/libfastjson/archive/v0.99.8.tar.gz
Summary  : a fast JSON implementation in C
Group    : Development/Tools
License  : MIT
Requires: libfastjson-lib = %{version}-%{release}
Requires: libfastjson-license = %{version}-%{release}

%description


%package dev
Summary: dev components for the libfastjson package.
Group: Development
Requires: libfastjson-lib = %{version}-%{release}
Provides: libfastjson-devel = %{version}-%{release}
Requires: libfastjson = %{version}-%{release}

%description dev
dev components for the libfastjson package.


%package lib
Summary: lib components for the libfastjson package.
Group: Libraries
Requires: libfastjson-license = %{version}-%{release}

%description lib
lib components for the libfastjson package.


%package license
Summary: license components for the libfastjson package.
Group: Default

%description license
license components for the libfastjson package.


%prep
%setup -q -n libfastjson-0.99.8
cd %{_builddir}/libfastjson-0.99.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604618060
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604618060
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libfastjson
cp %{_builddir}/libfastjson-0.99.8/COPYING %{buildroot}/usr/share/package-licenses/libfastjson/31c772b6e4ff5ccc00b3565e6dbdaeea24aab266
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libfastjson/atomic.h
/usr/include/libfastjson/json.h
/usr/include/libfastjson/json_object.h
/usr/include/libfastjson/json_object_iterator.h
/usr/include/libfastjson/json_object_private.h
/usr/include/libfastjson/json_tokener.h
/usr/include/libfastjson/json_util.h
/usr/lib64/libfastjson.so
/usr/lib64/pkgconfig/libfastjson.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libfastjson.so.4
/usr/lib64/libfastjson.so.4.2.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libfastjson/31c772b6e4ff5ccc00b3565e6dbdaeea24aab266
