#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libfastjson
Version  : 0.99.9
Release  : 9
URL      : https://github.com/rsyslog/libfastjson/archive/v0.99.9/libfastjson-0.99.9.tar.gz
Source0  : https://github.com/rsyslog/libfastjson/archive/v0.99.9/libfastjson-0.99.9.tar.gz
Summary  : a fast JSON implementation in C
Group    : Development/Tools
License  : MIT
Requires: libfastjson-lib = %{version}-%{release}
Requires: libfastjson-license = %{version}-%{release}

%description


%package dev
Summary: dev components for the libfastjson package.
Group: Development
Requires: libfastjson-lib = %{version}-%{release}
Provides: libfastjson-devel = %{version}-%{release}
Requires: libfastjson = %{version}-%{release}

%description dev
dev components for the libfastjson package.


%package lib
Summary: lib components for the libfastjson package.
Group: Libraries
Requires: libfastjson-license = %{version}-%{release}

%description lib
lib components for the libfastjson package.


%package license
Summary: license components for the libfastjson package.
Group: Default

%description license
license components for the libfastjson package.


%prep
%setup -q -n libfastjson-0.99.9
cd %{_builddir}/libfastjson-0.99.9
pushd ..
cp -a libfastjson-0.99.9 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656129824
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%autogen --disable-static
make  %{?_smp_mflags}

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
%autogen --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1656129824
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libfastjson
cp %{_builddir}/libfastjson-0.99.9/COPYING %{buildroot}/usr/share/package-licenses/libfastjson/31c772b6e4ff5ccc00b3565e6dbdaeea24aab266
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libfastjson/atomic.h
/usr/include/libfastjson/json.h
/usr/include/libfastjson/json_object.h
/usr/include/libfastjson/json_object_iterator.h
/usr/include/libfastjson/json_object_private.h
/usr/include/libfastjson/json_tokener.h
/usr/include/libfastjson/json_util.h
/usr/lib64/libfastjson.so
/usr/lib64/pkgconfig/libfastjson.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/glibc-hwcaps/x86-64-v3/libfastjson.so
/usr/lib64/glibc-hwcaps/x86-64-v3/libfastjson.so.4
/usr/lib64/glibc-hwcaps/x86-64-v3/libfastjson.so.4.3.0
/usr/lib64/libfastjson.so.4
/usr/lib64/libfastjson.so.4.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libfastjson/31c772b6e4ff5ccc00b3565e6dbdaeea24aab266
